### ISSUE TITLE
Readme.md update required.

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#1]
This URL shortener is written in django. So to execute it on local server a few steps are needed. How to clone, install dependencies, virtual environment install, commands in terminal (preferably Ubuntu or Fedora). Commands in other distros are welcome too!

**Comment by zorexsalvo** [comment]
How about containerized it via Docker? That way, you can run it on most of the machines.

**Comment by modihere** [comment]
If you are able to do that then you are welcome to do so.
See the thing is i don't have much idea about the docker and now since you have mentioned about it i will look into the details about it. This was just a free time web app i had made so i didn't go into much details about production. 
I would first of all recommend you to run the app and find a few bugs and if possible correct them and let me know. Then you can proceed to containerize it.
Will that be okay?
And i will be glad if you are able to do what you have asked. I will also get to learn a few things. :)
