### ISSUE TITLE
Create a .gitignore file for the project.

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#10]
List what you are going to add to the gitignore file before working on this issue.

**Comment by mohitkh7** [comment]
I will list following files and folders

db.sqlite3
shorturl/migrations
shorturl/__pycache__
shortweb/__pycache__

**Comment by modihere** [comment]
And the settings.py file as well. Better to upload settings.py.example while uploading. Anything else needed according to you?

**Comment by mohitkh7** [comment]
No Settings.py might get frequently updated and changed during the course of development as the project & codebase will expand. 
I don't think so that we should add settings.py file.
We can add wsgi.py file.

**Comment by modihere** [comment]
Yes that is what i am saying. People will change the settings.py according to their wishes and everyone will have his own settings.py in his or her PR. Sometimes the settings.py contains important information. So better create an example file providing the barebones of the whole thing and omit the original settings.py file while doing git push.
Another thing is that when you do a git pull from remote the settings.py may get changed creating confusions.

**Comment by mohitkh7** [comment]
Yes, got your point. we should include settings.py file also.
So the proposed list of files and folders in .gitignore is 
*.sqlite3
migrations/
__ pycache __ /
shortweb/settings.py
shortweb/wsgi.py
