### ISSUE TITLE
Add a check for proper URL in the address bar.

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#14]
The field accepts anything typed into it. Add a check for proper website.

**Comment by vchrombie** [comment]
Hello, Myself Venu Vardhan.
I am really interested in contributing to this project.

I have few doubts regarding this issue.
Can you help me ?

**Comment by vchrombie** [comment]
For validating a URL, should we implement the re python module to validate off of the RFC 3986 Reg-ex ?

Below is a snipped which should work?

* p = re.compile('^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?')
* m = p.match(url)
* if m:
  - self.url = url
  - return url

**Comment by modihere** [comment]
Seems a good approach. You may proceed. I will review it accordingly.

**Comment by modihere** [comment]
@vchrombie  are you working on this?

**Comment by vchrombie** [comment]
I want to do it.
But I need some time as I am busy.

Can you give me some time (may be one day) ?

**Comment by modihere** [comment]
Yeah okay. I will put up the assigned label.

**Comment by modihere** [comment]
Do you want to do it? or else i will be reassigning it to someone.

**Comment by vchrombie** [comment]
I will be doing it.
Sorry for the delay.

I am working on the implementation.

**Comment by aniketgattani** [comment]
@vchrombie are u working on this issue. If not I would like to work on it.

**Comment by vchrombie** [comment]
Ok
You can take that issue.
Sorry, I could not complete it.
