### ISSUE TITLE
Create a QR code for the shortened URL  and display it along side the shortened URL.

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#25]
If you want to get a much clear idea do take a look at soo.gd ( A URL shortening service)

**Comment by ghost** [comment]
I want to work on it.
Could you assign it to me?

**Comment by modihere** [comment]
Okay i have labelled it assigned. Just give me the barebones how you are going to work on this.

**Comment by ghost** [comment]
I am thinking of using module like 'qrcode' and use it in project. It will be displayed on the side as png image.

**Comment by modihere** [comment]
Will the QR code be generated locally or are you planning to use an API?

**Comment by ghost** [comment]
I was planning to use this module -https://pypi.python.org/pypi/PyQRCode and generate it locally.

**Comment by modihere** [comment]
Seems okay. Go for it.

**Comment by ghost** [comment]
I tried using PyQRCode but was unable to save it and send using jQuery. I tried django-qrcode too but the **data.url**  was not converting to url instead showed in QR code as just "data.url". So I looked for jquery script file and used that for QR code generation. 

I am sending pull request.
