### ISSUE TITLE
Create custom alias

### ISSUE THREAD

**Issue by sudharsana-kjl** [modihere/url-shortener#26]
An optional feature for creating a custom alias in the URL shortener such as http://url-shortner.com/alias-name in which the user enters the alias name.

**Comment by modihere** [comment]
What if that alias name is already in use?

**Comment by sudharsana-kjl** [comment]
Make it a unique field so that user can't add a duplicate value. This can be an optional feature for a user.

**Comment by modihere** [comment]
Yes, that's okay. Go on with the implementation then.

**Comment by modihere** [comment]
@aniketgattani assigned
