### ISSUE TITLE
Port to Django 1.11

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#5]

**Comment by mohitkh7** [comment]
Can You describe this issue bit more ?

**Comment by mohitkh7** [comment]
I updated my django version from 1.9.7 to 1.11.7 and whole project is running smooth and fine without any issue or error.

**Comment by modihere** [comment]
If everything is running fine then just update the requirements.txt

**Comment by mohitkh7** [comment]
Ok I will update requirements.txt
