### ISSUE TITLE
Make a good looking UI.

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#6]

**Comment by mohitkh7** [comment]
We can implement UI using either MaterializeCSS ( http://materializecss.com/ ) or flatly ( https://bootswatch.com/2/flatly/ )

**Comment by modihere** [comment]
Any attractive UI is acceptable. Commit your work file a PR. I will review it accordingly.

**Comment by modihere** [comment]
@mohitkh7  are you working on this? Then i will assign this to you.

**Comment by mohitkh7** [comment]
![screenshot 161](https://user-images.githubusercontent.com/19525624/33664615-452a2f2e-daba-11e7-90d5-0e47d7d50d8b.png)

**Comment by mohitkh7** [comment]
This is a sample UI I have designed.
Shall I proceed with it ?

**Comment by modihere** [comment]
Can you find a better background please? The fore ground and the backgound are very contrasting and its not looking so good. 
Check goo.gl or bit.ly or soo.gd to get some idea. You dont have to be hasty. Take your time. Around 3-4 days if you want and design a better one.

**Comment by mohitkh7** [comment]
![capture](https://user-images.githubusercontent.com/19525624/33673292-61b5e7d8-dad2-11e7-81b2-c312a9fd9fb7.JPG)

**Comment by mohitkh7** [comment]
Kindly review this UI.

**Comment by modihere** [comment]
Looks good. Just add some catchy pic instead of the dull blue background. Rest we will modify later accordingly.

**Comment by mohitkh7** [comment]
![capture](https://user-images.githubusercontent.com/19525624/33676376-9d83fc38-dadb-11e7-9dd0-2eeeae8d9934.JPG)

**Comment by modihere** [comment]
Yes, this is okay. Choose a proper font for the text. And align the text box at the centre of the page. Go on and commit and submit your PR.

**Comment by mohitkh7** [comment]
submitted the PR.
